# Generated by Django 4.2 on 2023-05-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_L1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_L2',
            field=models.BooleanField(default=False),
        ),
    ]
